In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(3, 3)

In [7]:
# checking memory efficiency
import sys
# creates a list of integers from 0 to 999
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [8]:
list1 = [1,2,3,4]
arr = np.array(list1)
list_squares = [x**2 for x in list1]
numpy_squares = arr**2

In [9]:
print(list_squares)
print(numpy_squares)

[1, 4, 9, 16]
[ 1  4  9 16]
