In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [4]:
arr1 = np.array([1, 2, 3, 4, 5]) # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
print(arr1) # [1 2 3 4 5]
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(1,100,9) # 1 to 99

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [10]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [12]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
myarr.shape

(4, 3)

In [14]:
myarr.size

12

In [15]:
myarr.ndim

2

In [16]:
myarr.dtype

dtype('int64')

In [17]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype='float32')

In [18]:
myarr.dtype

dtype('float32')

In [19]:
n = myarr.astype('float64')

In [20]:
n.dtype

dtype('float64')

In [21]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])


In [22]:
myarr.shape

(4, 3)

In [23]:
reshaped = myarr.reshape((3,4))

In [24]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])