In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
arr.shape

(4, 3)

In [5]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3]

np.int64(4)

In [9]:
flat[3:6]

array([4, 5, 6])

In [10]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:] # same as flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
flat[::2] # every second element

array([ 1,  3,  5,  7,  9, 11])

# concept

In [13]:
b = flat[3:7] # shallow copy -> no copy is created

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0] = 44444 # changes made to original array


In [16]:
b

array([44444,     5,     6,     7])

In [17]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [18]:
# deep copy

In [19]:
b = flat[3:7].copy()

In [20]:
b[0] = 66666

In [21]:
b

array([66666,     5,     6,     7])

In [22]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [23]:
# fancy indexing and boolean masking


In [24]:
arr = np.array([1,54,23,53,2,3,34,5,6])

In [25]:
arr[[1,4,6]]

array([54,  2, 34])

In [26]:
arr[arr>3]

array([54, 23, 53, 34,  5,  6])

In [27]:
arr[arr>23] # powerful way to filter large datasets

array([54, 53, 34])

In [28]:
# q

In [29]:
brr = np.array([1.1,2.2,3.3])

In [30]:
brr.shape

(3,)

In [31]:
brr.ndim

1

In [32]:
brr.dtype

dtype('float64')

In [33]:
crr = brr.astype('int64')

In [34]:
crr.dtype

dtype('int64')

In [35]:
brr.dtype

dtype('float64')

In [36]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [37]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr[arr>5]

array([6, 7, 8, 9])

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])