### Multidimentional Indexing and Axis in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[1]

array([4, 5, 6])

In [6]:
arr[2]

array([7, 8, 9])

In [7]:
arr[0][1]

np.int64(2)

In [8]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [9]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [10]:
arr[0][1]

np.int64(2)

In [11]:
arr[0,1]

np.int64(2)

In [12]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 3D arrays

In [15]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) # Output: (2, 2, 3)

(2, 2, 3)


In [16]:
arr3D # array of 2D arrays

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
# First sheet, second row, third column
print(arr3D[0, 1, 2]) # Output: 6
print(arr3D[:, 0, :]) # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [18]:
print(arr3D[0, 0, :])

[1 2 3]


In [19]:
print(arr3D[:, 0, 0])

[1 7]


In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
first_col = arr[:,0]
first_col

array([1, 4, 7])

In [22]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [23]:
# changing data along an axis
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


 
- Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)
- Indexing works as 
arr[row, column] for 2D arrays and 
[depth, row, column] for 3D arrays
- Slicing allows extracting subarrays
- Operations along axes help efficiently manipulate data without loops