## Data Types in NumPy

- NumPy arrays are homogeneous, meaning that they can only store elements of thesame type. 
- This is different from Python lists, which can hold mixed data types.

Common Data Types in NumPy:
- int32 , int64 : Integer types with different bit sizes.
- float32 , float64 : Floating-point types with different precision.
- bool : Boolean data type.
- complex64 , complex128 : Complex number types.
- object : For storing objects (e.g., Python objects, strings).

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.astype('float64')

array([1., 2., 3., 4.])

In [6]:
# downcasting to save memory

In [7]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)

In [8]:
arr_large.dtype

dtype('int64')

In [9]:
arr_small = arr_large.astype(np.int32)

In [10]:
arr_small

array([1000000, 2000000, 3000000], dtype=int32)

In [11]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes) # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes) # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [12]:
# string data type in NumPy
# However, working with strings in NumPy is less efficient than using lists or Python’s built-in string types.

In [13]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10') # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [14]:
arr.dtype

dtype('<U10')

In [15]:
# Complex Numnbers
# NumPy also supports complex numbers, which consist of a real and imaginary part. 

In [16]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [17]:
# Object data type
# If you need to store mixed or complex data types (e.g., Python objects), you can use dtype='object'.  
# However, this type sacrifices performance, so it should only be used when absolutely necessary.

In [18]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


In [19]:
arr.dtype

dtype('O')

 Choosing the Right Data Type
 - Choosing the correct data type is essential for: - Optimizing memory: Using the
smallest data type that fits your data. - Improving performance: Smaller types
generally lead to faster operations. - Ensuring precision: Avoid truncating or losing
important decimal places or values.