## Broadcasting in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = []
# Using a loop to square each element (slow)
for num in arr:
    result.append(num**2)
print(result) # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectorized operation
print(result) # Output: [1 4 9 16 25]
print(result.dtype)

[ 1  4  9 16 25]
int64


Vectorization allows you to perform operations on entire arrays at once, instead of
iterating over elements one by one. This is made possible by NumPy’s optimized
C-based backend that executes operations in compiled code, which is much faster
than Python loops.

Why is it Faster?

- Low-level implementation: NumPy’s vectorized operations are implemented
in C (compiled language), which is much faster than Python loops.
- Batch processing: NumPy processes multiple elements in parallel using SIMD
(Single Instruction, Multiple Data), allowing multiple operations to be done
simultaneously.

### Broadcasting: Scaling Arrays Without Extra Memory

Broadcasting is a powerful feature of NumPy that allows you to perform
operations on arrays of different shapes without creating copies. It “stretches”
smaller arrays across larger arrays in a memory-efficient way, avoiding the
overhead of creating multiple copies of data.

In [4]:
arr = np.array([1, 2, 3, 4, 5])
# Broadcasting: 10 is added to all elements
result = arr + 10 
print(result) 

[11 12 13 14 15]


In [5]:
# Here, the scalar 10 is “broadcast” across the entire array, and no extra memory is used

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2  # Element-wise addition
print(result) # Output: [11 22 33]

[11 22 33]


In [7]:
# Example: Broadcasting a 2D Array and a 1D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In this case, arr2 is broadcast across the rows of arr1, adding [1,2,3] to each row.
How Broadcasting Works:
- Dimensions must be compatible: The size of the trailing dimensions of the
arrays must be either the same or one of them must be 1.
- Stretching arrays: If the shapes are compatible, NumPy stretches the smaller
array to match the larger one, element-wise, without copying data.

In [8]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])


In [10]:
arr = (arr - 1) / 2

In [11]:
arr

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

Summary:
- Loops are slow because Python’s interpreter adds overhead, making iteration
less efficient.
- Vectorization allows you to apply operations to entire arrays at once, greatly
improving performance by utilizing NumPy’s optimized C backend.
- Broadcasting enables operations between arrays of different shapes by
automatically stretching the smaller array to match the shape of the larger
array, without creating additional copies.
- Real-world use: Broadcasting can be used in data science tasks, such as 
normalizing datasets, without sacrificing memory or performance.