## Built in Mathematical Functions in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([3,5,2,33])

In [3]:
arr

array([ 3,  5,  2, 33])

In [4]:
arr.dtype

dtype('int64')

In [5]:
# np.mean() – Compute the mean (average) of an array.
np.mean(arr)

np.float64(10.75)

In [6]:
# np.max() – Compute the maximum value of an array.
np.max(arr)

np.int64(33)

In [7]:
# np.min() – Compute the minimum value of an array
np.min(arr)

np.int64(2)

In [8]:
# np.std() – Compute the standard deviation of an array
np.std(arr)

np.float64(12.891373084353738)

In [9]:
# np.var() – Compute the variance of an array
np.var(arr)

np.float64(166.1875)

In [10]:
# np.sum() – Compute the sum of all elements in an array
np.sum(arr)

np.int64(43)

In [11]:
# np.prod() – Compute the product of all elements in an array
np.prod(arr)

np.int64(990)

In [12]:
# np.median() – Compute the median of an array.
np.median(arr)

np.float64(4.0)

In [13]:
# np.percentile() – Compute the percentile of an array
np.percentile(arr, 50)

np.float64(4.0)

In [14]:
# np.argmin() – Return the index of the minimum value in an array
np.argmin(arr)

np.int64(2)

In [15]:
# np.argmax() – Return the index of the maximum value in an array
np.argmax(arr)

np.int64(3)

In [16]:
# np.unique() – Find the unique elements of an array
np.unique(arr)

array([ 2,  3,  5, 33])

In [17]:
# np.diff() – Compute the n-th differences of an array.
np.diff(arr)

array([ 2, -3, 31])

In [18]:
# np.cumsum() – Compute the cumulative sum of an array
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [19]:
arr

array([ 3,  5,  2, 33])

In [20]:
# np.log() – Compute the natural logarithm of an array
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [21]:
# np.exp() – Compute the exponential of an array
np.exp(arr)


array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])